---
abstract: 'A weighted graph implementation'
author:
  - 'Gene Boggs <gene@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300015, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Graph-Weighted
requires:
  Graph: 0
  base: 0
  constant: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Graph-Weighted
  repository: https://github.com/ology/Math/tree/master/Graph-Weighted
version: 0.5
