--- #YAML:1.0
name:                Graph-Weighted
version:             0.14_1
abstract:            OBSOLETE - An abstract, weighted graph implementation
license:             ~
author:              
    - Gene Boggs <gene@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.38
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
