#!/usr/bin/perl
use strict;
use warnings;
use Graph::Weighted;
my $g = Graph::Weighted->new;
my $data = [
    [ 0, 1, 2, 0, 0, ],
    [ 1, 0, 3, 0, 0, ],
    [ 2, 3, 0, 0, 0, ],
    [ 0, 0, 1, 0, 0, ],
    [ 0, 0, 0, 0, 0, ],
];
$g->populate($data);

for my $v ($g->vertices) {
    my $w = $g->get_weight($v);
warn"V: $v = $w\n";
}

for my $e ($g->edges) {
    my $w = $g->get_edge_weight(@$e);
warn"E: @$e = $w\n";
}
